# Generated by Django 3.1 on 2020-08-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnitAnalysis',
            fields=[
                ('ID', models.UUIDField(blank=True, primary_key=True, serialize=False)),
                ('CAMPAIGN_ID', models.UUIDField(blank=True)),
                ('NAME', models.CharField(blank=True, max_length=200, null=True)),
                ('TYPE', models.IntegerField(default=0)),
                ('KEY_MAIN', models.CharField(blank=True, max_length=200, null=True)),
                ('KEY_EXTRA', models.CharField(max_length=200, null=True)),
                ('KEY_EXCLUDE', models.CharField(max_length=200, null=True)),
                ('KEY_PLACE', models.CharField(max_length=200, null=True)),
                ('CREATE_DATE', models.DateTimeField(auto_now_add=True)),
                ('UPDATE_DATE', models.DateTimeField(auto_now=True)),
                ('VERSION', models.IntegerField(blank=True, default=0)),
                ('ACTIVE', models.BooleanField(blank=True)),
            ],
        ),
    ]
