# Generated by Django 3.1 on 2020-08-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResults',
            fields=[
                ('ID', models.UUIDField(primary_key=True, serialize=False)),
                ('UNIT_ANALYSIS_ID', models.UUIDField()),
                ('PERIOD', models.CharField(max_length=200)),
                ('POSITIVE_INDICATOR', models.IntegerField(default=0)),
                ('NEGATIVE_INDICATOR', models.IntegerField(default=0)),
                ('NEUTRAL_INDICATOR', models.IntegerField(default=0)),
                ('TOTAL_MENTION', models.IntegerField(default=0)),
                ('TOTAL_INTERACTIVE', models.IntegerField(default=0)),
                ('CREATE_DATE', models.DateTimeField(auto_now=True, verbose_name='Thời gian khởi tạo')),
                ('UPDATE_DATE', models.DateTimeField(auto_now=True, verbose_name='Thời gian chỉnh sửa')),
                ('VERSION', models.IntegerField(default=0)),
                ('ACTIVE', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='unitanalysis',
            name='CREATE_DATE',
            field=models.DateTimeField(auto_now=True, verbose_name='Thời gian khởi tạo'),
        ),
        migrations.AlterField(
            model_name='unitanalysis',
            name='ID',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unitanalysis',
            name='KEY_PLACE',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='unitanalysis',
            name='NAME',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='unitanalysis',
            name='UPDATE_DATE',
            field=models.DateTimeField(auto_now=True, verbose_name='Thời gian chỉnh sửa'),
        ),
    ]
