# Generated by Django 3.1 on 2020-08-30 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200828_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresults',
            name='UNIT_ANALYSIS_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.unitanalysis'),
        ),
    ]
