# Generated by Django 3.1 on 2020-09-04 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0006_auto_20200830_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('ID', models.UUIDField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=200)),
                ('CREATE_DATE', models.DateTimeField(auto_now_add=True)),
                ('UPDATE_DATE', models.DateTimeField(auto_now=True)),
                ('VERSION', models.IntegerField(default=0)),
                ('ACTIVE', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='unitanalysis',
            name='CAMPAIGN_ID',
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('ID', models.UUIDField(primary_key=True, serialize=False)),
                ('TYPE', models.CharField(max_length=200)),
                ('DOMAIN', models.CharField(max_length=200)),
                ('TITLE', models.CharField(max_length=200)),
                ('CONTENT', models.CharField(max_length=200)),
                ('IMAGE', models.CharField(max_length=200)),
                ('ICON', models.CharField(max_length=200)),
                ('LINK', models.CharField(max_length=200)),
                ('SUB_CONTENT', models.CharField(max_length=200)),
                ('MARKER', models.BooleanField()),
                ('STATUS', models.BooleanField()),
                ('CREATE_DATE', models.DateTimeField(auto_now_add=True)),
                ('UPDATE_DATE', models.DateTimeField(auto_now=True)),
                ('VERSION', models.IntegerField(default=0)),
                ('ACTIVE', models.BooleanField()),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cumstomer',
            fields=[
                ('ID', models.UUIDField(primary_key=True, serialize=False)),
                ('LAST_MIDDLE_NAME', models.CharField(max_length=200)),
                ('FIRST_NAME', models.CharField(max_length=200)),
                ('EMAIL', models.CharField(max_length=200)),
                ('COMPANY_FIELDS', models.CharField(max_length=200)),
                ('JOB_POSITION', models.CharField(max_length=200)),
                ('CREATE_DATE', models.DateTimeField(auto_now_add=True)),
                ('UPDATE_DATE', models.DateTimeField(auto_now=True)),
                ('VERSION', models.IntegerField(default=0)),
                ('ACTIVE', models.BooleanField()),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
